# WHAT IS PYTORCH?

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[6.8469e-39, 4.5647e-41, 6.8469e-39],
        [4.5647e-41, 3.0357e+32, 1.3563e-19],
        [1.1290e+27, 1.8037e+28, 2.6454e+20],
        [2.8492e+20, 5.0850e+31, 1.9421e+31],
        [3.6002e+27, 8.8674e-04, 6.2717e+22]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8752, 0.6258, 0.4730],
        [0.4716, 0.0307, 0.9342],
        [0.6358, 0.0258, 0.6814],
        [0.9170, 0.7466, 0.5417],
        [0.9182, 0.7499, 0.9256]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3798,  0.0290,  1.5947],
        [ 0.9662,  1.2938,  0.8570],
        [ 0.3370, -0.2184,  0.9449],
        [-0.0904,  1.0376,  0.5206],
        [-2.8881, -1.3382, -1.6332]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.4911,  0.5344,  2.4431],
        [ 1.7668,  1.5887,  1.1501],
        [ 0.9182,  0.6714,  1.1644],
        [ 0.1928,  1.2104,  0.7012],
        [-2.4709, -0.7604, -1.4684]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.4911,  0.5344,  2.4431],
        [ 1.7668,  1.5887,  1.1501],
        [ 0.9182,  0.6714,  1.1644],
        [ 0.1928,  1.2104,  0.7012],
        [-2.4709, -0.7604, -1.4684]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.4911,  0.5344,  2.4431],
        [ 1.7668,  1.5887,  1.1501],
        [ 0.9182,  0.6714,  1.1644],
        [ 0.1928,  1.2104,  0.7012],
        [-2.4709, -0.7604, -1.4684]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.4911,  0.5344,  2.4431],
        [ 1.7668,  1.5887,  1.1501],
        [ 0.9182,  0.6714,  1.1644],
        [ 0.1928,  1.2104,  0.7012],
        [-2.4709, -0.7604, -1.4684]])


In [12]:
print(x[:, 1])

tensor([ 0.0290,  1.2938, -0.2184,  1.0376, -1.3382])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3863])
-0.3862896263599396


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.6137], device='cuda:0')
tensor([0.6137], dtype=torch.float64)
